Repository pnu-004-team4/team04, pull requests merged in 2019-06, with the labels that each got.

#71 Sort binding done
  src/main/resources/static/js/listControl.js
  src/main/webapp/WEB-INF/jsp/Player/player.jsp
Labels: enhancement

#72 Added import statement which was removed while resolving a conflict
  src/main/webapp/WEB-INF/jsp/Player/player.jsp
Labels: bug

#77 Audio.setAudioMeta(audio) doesn't duplicate its content + test cases
  src/main/java/com/team04/musiccloud/audio/Audio.java
  src/main/java/com/team04/musiccloud/audio/AudioMeta.java
  src/test/java/com/team04/musiccloud/audio/AudioMetaBuilderTest.java
  src/test/java/com/team04/musiccloud/audio/AudioTest.java
  src/test/java/com/team04/musiccloud/audio/FileMetaBuilderTest.java
  src/test/java/com/team04/musiccloud/audio/FileMetaTest.java
  src/test/java/com/team04/musiccloud/utilities/DateTimeUtilitiesTest.java
  src/test/java/com/team04/musiccloud/utilities/FileSystemUtilitiesTest.java
  src/test/java/com/team04/musiccloud/utilities/FunctionUtilitiesTest.java
  src/test/java/com/team04/musiccloud/utilities/NumberUtilitiesTest.java
  src/test/java/com/team04/musiccloud/utilities/StaticPathsTest.java
  src/test/java/com/team04/musiccloud/utilities/StringUtilitiesTest.java
  src/test/java/com/team04/musiccloud/utilities/network/NetStatusManagerTest.java
  src/test/java/com/team04/musiccloud/utilities/network/UserNetStatusTest.java
  src/test/java/com/team04/musiccloud/utilities/structure/FixedDequeTest.java
  src/test/java/com/team04/musiccloud/utilities/structure/OverSizeLimitExceptionTest.java
  src/test/java/com/team04/musiccloud/utilities/structure/UpdateDequeTest.java
Labels: enhancement

#79 Fixed sorting not working after adding new audio (resolves #78)
  src/main/resources/static/js/listControl.js
  src/main/webapp/WEB-INF/jsp/Player/player.jsp
Labels: bug

#96 각종 이슈 사항 처리
  .gitignore
  src/main/java/com/team04/musiccloud/audio/AudioHandler.java
  src/main/java/com/team04/musiccloud/auth/AccountService.java
  src/main/java/com/team04/musiccloud/controller/PlayerController.java
  src/main/java/com/team04/musiccloud/controller/SampleStreamingController.java
  src/main/java/com/team04/musiccloud/controller/SenderController.java
  src/main/java/com/team04/musiccloud/controller/SettingController.java
  src/main/java/com/team04/musiccloud/controller/UploadController.java
  src/main/java/com/team04/musiccloud/stream/caching/AudioCollector.java
  src/main/resources/static/css/myPlayer.css
  src/main/resources/static/js/listControl.js
  src/main/resources/static/js/myPlayer.js
  src/main/webapp/WEB-INF/jsp/Setting/setting.jsp
  src/test/java/com/team04/musiccloud/stream/StreamingTest.java
  src/test/java/com/team04/musiccloud/stream/transcode/TranscodeTest.java
Labels: bug, enhancement
